language: generic
sudo: required
dist: trusty
notifications:
  email: false

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev
  - sudo apt-get install -y libboost-program-options-dev libboost-filesystem-dev
  - sudo apt-get install g++-5
  - sudo apt-get install expect

  - "cd /usr/src/gtest && sudo cmake -DBUILD_SHARED_LIBS=ON . && sudo make && sudo mv libgtest* /usr/local/lib/; cd -"

script:
  - mkdir BUILD
  - cd BUILD
  - cmake ..
  - make
  - make test

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5 CTEST_OUTPUT_ON_FAILURE=1
