language: generic
sudo: required
dist: trusty
notifications:
  email: false
env:
  global:
     - GTEST_ROOT=/tmp/gtest
   
addons:
  apt:
    update: true
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - libgtest-dev
      - g++-5
      - expect
      - libboost-program-options-dev
      - libboost-filesystem-dev

before_script:
  - mkdir -p /tmp/gtest
  - cd /tmp/gtest
  - cmake -DBUILD_SHARED_LIBS=ON /usr/src/gtest
  - make
  - cd -
script:
  - mkdir BUILD
  - cd BUILD
  - cmake ..
  - make
  - make test

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5 CTEST_OUTPUT_ON_FAILURE=1
